version: '3'

services:
  app:
      container_name: "app"
      command: bash -c "./myapp"
      build: ./
      volumes:
        - ./src:/go/src/Go300-backend/src
      working_dir: /go/src/Go300-backend/src
      ports:
        - 8000:8000
      depends_on:
        - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=Go300
      - MONGO_INITDB_ROOT_PASSWORD=default
      - MONGO_INITDB_DATABASE=Go300DB
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
